name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest

      - name: CMake - Preconfigure
        run: cmake -B build -DCMAKE_CXX_COMPILER=$PWD/scripts/zigcxx.sh

      - name: CMake - Build C++ client
        run: cmake --build build --target run_with_tb

      - name: Zig - Build C++ client
        run: zig build --summary all -freference-trace

  zig-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [{ msystem: CLANG64, arch: x86_64, prefix: /clang64 }]
    steps:
      - uses: actions/checkout@v3
        with:
          path: temp
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          path-type: inherit
          location: D:\
          install: git mingw-w64-clang-${{ matrix.arch }}-cmake mingw-w64-clang-${{ matrix.arch }}-toolchain
          update: true
      
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CMake Build - ${{ matrix.arch }}
        shell: msys2 {0}
        run: |
            cd /C/_
            cmake -B build \
            -DTIGERBEETLE_BUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Debug

            cmake --build build --config debug --parallel

      - name: Build Summary - ${{ matrix.arch }}
        shell: msys2 {0}
        run: |
            cd /C/_
            zig build --summary all -freference-trace -Dtarget=${{ matrix.arch }}-windows
