name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '13 8 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest

      - name: CMake - Configure
        run: cmake -B build -DUSE_FMT=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release

      - name: CMake - Build C++ client
        run: cmake --build build --target run_with_tb

      - name: Zig - Build C++ client
        run: zig build --summary all -freference-trace

  msys2-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - { sys: mingw64, env: x86_64 } # msvcrt + libstdc++
        - { sys: ucrt64,  env: ucrt-x86_64 } # ucrt + libstdc++
        - { sys: clang64, env: clang-x86_64 } # ucrt + libc++
    steps:
      - uses: actions/checkout@v3
        with:
          path: temp
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          path-type: inherit
          location: D:\
          install: git mingw-w64-${{matrix.env}}-cmake mingw-w64-${{matrix.env}}-toolchain
          update: true
      
      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CMake - Configure
        shell: msys2 {0}
        run: |
            cd /C/_
            cmake -B build -DUSE_FMT=ON -DBUILD_EXAMPLES=ON
      
      - name: CMake - Build C++ client
        shell: msys2 {0}
        run: |
            cd /C/_
            cmake --build build --parallel

      - name: Zig - Build C++ client
        shell: msys2 {0}
        run: |
            cd /C/_
            zig build --summary all -freference-trace
